pub static MATCH_ERROR_ORDER_NOT_FOUND:u32 = 1;
pub static MATCH_ERROR_AMOUNT_TOO_SMALL:u32 = 2;
pub static MATCH_ERROR_ORDER_COUNT_LIMIT:u32 = 3;
pub static MATCH_ERROR_MARKET_ORDER_EMPTY_RIVAL:u32 = 4;